### ISSUE TITLE
Assets missing?

### ISSUE THREAD

**Issue by hoseyjoe** [RblSb/Kha-TilemapScrolling#1]
ha-TilemapScrolling\src/Lvl.hx:48: characters 13-36 : kha._Assets.BlobList has no field tiles_json (Suggestion: _tiles_json)
Kha-TilemapScrolling\src/Screen.hx:141: characters 11-40 : kha._Assets.FontList has no field OpenSans_Regular (Suggestions: _OpenSans_Regular, _OpenSans_RegularName, _OpenSans_RegularLoad)

**Comment by RblSb** [comment]
You need to update the submodule https://github.com/Kode/khamake to the master branch, this problem was fixed a few days ago =)

**Comment by RblSb** [comment]
Also updated in Kha itself
